### ISSUE TITLE
How to actually put this into a website?

### ISSUE THREAD

**Issue by Jop-V** [emojidex/emojidex-web#15]
The demo page source does not make it very clear.

**Comment by Kagetsuki** [comment]
@Jop-V We actually hadn't had the time to really focus on this so our documentation, as you have noted, is currently not too great. I'm having @snowsunny write it up now and I'll ping you once we have it up (hopefully by the end of the day here). I'll keep this issue open until you have it integrated. After we put up the more detailed documentation please don't hesitate to ask questions or point out any issues you have here.

**Comment by Jop-V** [comment]
No need to hurry :smiley:

**Comment by Kagetsuki** [comment]
@Jop-V we've update the docs and the demo and ended up doing some minor updates and polishing. If you can take a look and see if everything is clear enough to implement please tell me. If you had difficulty understanding anything or encounter any issues please write them down here.

Thanks for your patience!

**Comment by Kagetsuki** [comment]
@Jop-V Any luck?

**Comment by Jop-V** [comment]
Thanks! :+1: I haven't tested `emojidexAutocomplete` since `emojidexReplace` is all I need at the moment.

**Comment by Kagetsuki** [comment]
@Jop-V Rock on! We've got quite a few more features we plan to implement once we have the time. If you find any issues or have any feature requests please don't hesitate to tell us.
